### ISSUE TITLE
Relative links + navigation

### ISSUE THREAD

**Issue by SgtCoDFish** [zentered/next-product-docs#4]
@PatrickHeneise asked me to raise this issue relating to relative links on https://cert-manager.io/

An issue I have is that I can't go "up" past the docs version. For example on the v1.8-docs, on [this page](https://cert-manager.io/v1.8-docs/installation/helm/)

I want `Install a supported version of Kubernetes or OpenShift` to link to `/docs/installation/supported-releases.md` - this is important since `supported-releases.md` doesn't exist on anything except `/docs`.

None of the expected links work:

* `../../../docs/installation/supported-releases.md`ends up linking to `/v1.8-docs/installation/installation/supported-releases/`
* So does `../../docs/installation/supported-releases.md` and `../../../../docs/installation/supported-releases.md` (both are wrong but illustrate the problem)
* So does `/docs/installation/supported-releases.md`

It doesn't actually seem possible to link to a different docs version in any case. It'd be nice to be able to use relative links for this.

Another example of this issue would be going from pages under `/docs/release-notes`, where we might want to link to version-specific documentation. E.g. on [/docs/release-notes/release-notes-1.8](https://cert-manager.io/docs/release-notes/release-notes-1.8#server-side-apply) we might want the "controller flag" link to link to `https://cert-manager.io/v1.8-docs/cli/controller` and not `https://cert-manager.io/docs/cli/controller` as it does currently (since the `--feature-gates` controller flag might not mention the feature in future versions of cert-manager, where the feature may no longer be feature gates)

**Comment by PatrickHeneise** [comment]
I published `v0.0.117` (1f581d4) with these additional cases:

`../../v1.8-docs/cli/controller.md`
`../../docs/installation/supported-releases.md`

Let me know if that works.

**Comment by SgtCoDFish** [comment]
I just tried locally with `npm i @zentered/next-product-docs@0.0.119` and still see broken behaviour on http://localhost:3000/v1.8-docs/installation/helm/

With the file as it is on `master` (i.e. `../../installation/supported-releases/`) the first link is broken as expected but the second is now always broken:

```text
- Install a [supported version of Kubernetes or OpenShift](http://localhost:3000/installation/supported-releases/).
- Read [Compatibility with Kubernetes Platform Providers](http://installation/compatibility) if you are using Kubernetes on a cloud platform.
```

With the file modified (i.e. `../../../docs/installation/supported-releases.md`) the first link looks correct but the second link - which is totally unchanged from master - still becomes broken:

```text
- Install a [supported version of Kubernetes or OpenShift](http://localhost:3000/docs/installation/supported-releases).
- Read [Compatibility with Kubernetes Platform Providers](http://installation/compatibility) if you are using Kubernetes on a cloud platform.
```

Compare to master (currently https://cert-manager.io/v1.8-docs/installation/helm/):

```text
- Install a [supported version of Kubernetes or OpenShift](https://cert-manager.io/v1.8-docs/installation/installation/supported-releases/).
- Read [Compatibility with Kubernetes Platform Providers](https://cert-manager.io/v1.8-docs/installation/compatibility) if you are using Kubernetes on a cloud platform.
```

**Comment by PatrickHeneise** [comment]
Should finally be resolved with 9a3c8d2. Thanks for reporting the issues!

**Comment by SgtCoDFish** [comment]
Looks to be fixed in the latest version, thanks very much :+1:
